name: Java CI with Maven

on:
  workflow_call:
    inputs:
      context_path:
        required: false
        type: string
        description: "Set the context path"
        default: '.'
      skip_tests:
        required: false
        type: string
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=${{ inputs.skip_tests }}
